sudo: required
services:
 - docker
before_install:
 - docker build -t vamsi0710/react-test -f ./client/Dockerfile.deb ./client

script:
 - docker run -e CI=true vamsi0710/react-test npm test

after_success:
 - docker build -t vamsi0710/multi-client ./client
 - docker build -t vamsi0710/multi-nginx ./nginx
 - docker build -t vamsi0710/multi-server ./server
 - docker build -t vamsi0710/multi-worker ./worker
# Log in to Docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
#Take images and pust to Dockerhub
 - docker push vamsi0710/multi-client
 - docker push vamsi0710/multi-nginx
 - docker push vamsi0710/multi-server
 - docker push vamsi0710/multi-worker
